-- XP Bar Enhanced - Sigil Skins
-- Pure data + resolution for the Sigil style. No widget calls, no frame
-- references: everything level- and class-dependent lives here so it can be
-- reasoned about (and printed from `/xpbe sigil debug`) independently of art.

local Addon = XPBarEnhanced
Addon.SigilSkins = Addon.SigilSkins or {}

---@class SigilSkins
local SigilSkins = Addon.SigilSkins

local L = Addon.L

-------------------------------------------------------------------
-- TIERS
-------------------------------------------------------------------

-- Fractions of GetMaxPlayerLevel(), never literal levels, so the bands track
-- the cap across expansions. At cap 80 these land as 1-19 / 20-43 / 44-67 /
-- 68-80. Adding a fifth tier is: append a fraction, add the art.
SigilSkins.TIER_FRACTIONS = {0.00, 0.25, 0.55, 0.85}

SigilSkins.MAX_TIER = #SigilSkins.TIER_FRACTIONS

-------------------------------------------------------------------
-- CLASS FAMILIES
-------------------------------------------------------------------

-- Families are the motif grouping for the art, not a runtime behaviour: they
-- let an artist batch a coherent set rather than invent 13 vocabularies. All 13
-- retail class tokens are covered. Note the tokens carry no separator --
-- DEATHKNIGHT and DEMONHUNTER, not DEATH_KNIGHT / DEMON_HUNTER.
SigilSkins.FAMILY_BY_CLASS = {
    MAGE        = "arcane",
    WARLOCK     = "arcane",
    PRIEST      = "sacred",
    PALADIN     = "sacred",
    DRUID       = "wild",
    SHAMAN      = "wild",
    HUNTER      = "wild",
    WARRIOR     = "martial",
    DEATHKNIGHT = "martial",
    MONK        = "martial",
    ROGUE       = "umbral",
    DEMONHUNTER = "umbral",
    EVOKER      = "draconic",
}

-------------------------------------------------------------------
-- SKINS
-------------------------------------------------------------------

local ART = "Interface\\AddOns\\XPBarEnhanced\\assets\\"

-- Never offered in the options dropdown. Halo exists only as the forced
-- fallback for when the bar is not tracking XP, and as the art-less stand-in
-- while a skin's tier art does not exist yet.
SigilSkins.INTERNAL = {halo = true}

SigilSkins.skins = {
    -- Procedural: no TGA at all. Tier reads as geometry -- concentric arcs,
    -- then outer ticks, then a bloom -- so it is shippable before any art is
    -- drawn and is what the max-level repurpose and companion bar always use.
    halo = {
        id = "halo",
        label = (L and L["SKIN_HALO"]) or "Halo",
        accent = "class",
        procedural = true,
        internal = true,
        band = {
            [1] = {arcs = 1, ticks = 0},
            [2] = {arcs = 2, ticks = 0},
            [3] = {arcs = 2, ticks = 16},
            [4] = {arcs = 3, ticks = 24, bloom = 0.35},
        },
    },

    -- Flagship: shipped greyscale TGA, tinted at runtime. The casing and rune
    -- band are class-agnostic; only the crest carries the class. `casing` and
    -- `band` are sparse by design -- Resolve walks down -- so the art can land
    -- one tier at a time without a code change or a config migration.
    sigil = {
        id = "sigil",
        label = (L and L["SKIN_SIGIL"]) or "Sigil",
        accent = "class",
        -- All four shipped. The table stays sparse-tolerant on purpose: remove
        -- an entry and ResolveLayer walks down to the next one below it rather
        -- than rendering an empty ring, and emptying it entirely falls all the
        -- way back to halo. Generated by assets/raw/generate_sigil.py.
        casing = {
            [1] = ART .. "sigil-casing-1",
            [2] = ART .. "sigil-casing-2",
            [3] = ART .. "sigil-casing-3",
            [4] = ART .. "sigil-casing-4",
        },
        -- %s = lower-cased class token; the tier picks a quarter of the 2x2
        -- atlas via SetTexCoord, so a tier change costs no texture swap.
        bandTexture = ART .. "sigil-runes-%s",
        crestTexture = ART .. "sigil-crest-%s",
    },
}

-------------------------------------------------------------------
-- QUERIES
-------------------------------------------------------------------

--- Skins offered in the options dropdown. Never includes internal fallbacks.
---@return table list Array of {value = id, label = string}
function SigilSkins:GetSelectable()
    local list = {}
    for id, skin in pairs(self.skins) do
        if not skin.internal then
            list[#list + 1] = {value = id, label = skin.label or id}
        end
    end
    -- pairs() order is undefined; sort so the dropdown is stable between sessions.
    table.sort(list, function(a, b) return a.value < b.value end)
    return list
end

--- The art family for a class token, or nil for an unknown/absent token.
---@param classToken string|nil
---@return string|nil family
function SigilSkins:GetFamily(classToken)
    if type(classToken) ~= "string" then
        return nil
    end
    return self.FAMILY_BY_CLASS[classToken]
end

--- Resolve the tier band a level falls into.
--- Guards maxLevel: GetMaxPlayerLevel() can return 0 during early login, and
--- `level / 0` is inf, which compares >= against every fraction and would pin
--- the player to the top tier on every login.
---@param level number|nil
---@param maxLevel number|nil
---@return number tier 1..MAX_TIER
function SigilSkins:ResolveTier(level, maxLevel)
    local cap = tonumber(maxLevel) or 0
    local current = tonumber(level) or 1
    local frac = (cap > 0) and (current / cap) or 0

    local tier = 1
    for index, cut in ipairs(self.TIER_FRACTIONS) do
        if frac >= cut then
            tier = index
        end
    end
    return tier
end

--- Resolve the drawable layer description for a skin at a tier.
---
--- Walks *down* to the highest defined entry at or below the requested tier, so
--- a sparse table (tiers 1 and 4 only) is legal and every intermediate art state
--- is shippable.
---
--- When nothing is defined at or below the tier -- the flagship before its art
--- exists -- this returns nil, and Resolve substitutes halo. Without that
--- substitution a levelling character would resolve the flagship, SetTexture
--- against missing files, and render a bare masked fill with no ring at all.
---@param skin table|nil
---@param tier number
---@return table|nil layer
---@return number|nil resolvedTier The tier the layer was actually found at
function SigilSkins:ResolveLayer(skin, tier)
    if type(skin) ~= "table" then
        return nil, nil
    end

    local source = skin.procedural and skin.band or skin.casing
    if type(source) ~= "table" then
        return nil, nil
    end

    for index = tier, 1, -1 do
        local entry = source[index]
        if entry ~= nil then
            -- A procedural entry is a table of numbers; a flagship entry is a
            -- texture path. Normalise so callers get one shape.
            if type(entry) == "table" then
                return entry, index
            end
            return {texture = entry}, index
        end
    end

    return nil, nil
end

--- Resolve the accent colour for a skin.
--- `accent = "class"` uses the player's class colour when the user has not
--- turned it off; otherwise the configured XP bar colour is used.
---@param skin table|nil
---@param classToken string|nil
---@return table accent {r, g, b}
function SigilSkins:ResolveAccent(skin, classToken)
    local useClassColor = true
    local Config = Addon.Config
    if Config and Config.GetOptionValue then
        local saved = Config:GetOptionValue("sigilUseClassColor")
        if saved ~= nil then
            useClassColor = saved and true or false
        end
    end

    if skin and skin.accent == "class" and useClassColor and type(classToken) == "string" then
        local colors = _G.RAID_CLASS_COLORS
        local c = colors and colors[classToken]
        if c then
            return {r = c.r, g = c.g, b = c.b}
        end
    end

    -- Fall back to the configured XP bar colour so the ring never renders
    -- uncoloured, including for an unknown class token.
    local Colors = Addon.Colors
    if Colors and Colors.Get and Colors.Key then
        local c = Colors:Get(Colors.Key.XpBar)
        if c and c.r then
            return {r = c.r, g = c.g, b = c.b}
        end
    end

    return {r = 0.58, g = 0.51, b = 0.79}
end

--- The single entry point: resolve everything the style needs to paint itself.
---
--- Never errors. An unknown class token yields a nil family -- the casing is
--- class-agnostic, so the ring still draws, just with no crest and no rune
--- strip. An unknown skin id falls back to the flagship, which in turn falls
--- back to halo while its art table is empty.
---@param level number|nil
---@param maxLevel number|nil
---@param skinId string|nil
---@param classToken string|nil
---@param isXPMode boolean|nil false when repurposed for a secondary source
---@return number tier
---@return table skin
---@return table|nil layer nil only if even halo has no entry at or below the tier
---@return table accent
function SigilSkins:Resolve(level, maxLevel, skinId, classToken, isXPMode)
    -- Not tracking XP (max-level repurpose, companion bar) => halo, tier-less.
    -- One rule, applied in one place: tier art means XP, halo means everything
    -- else.
    if isXPMode == false then
        local halo = self.skins.halo
        local layer = self:ResolveLayer(halo, 1)
        return 1, halo, layer, self:ResolveAccent(halo, classToken)
    end

    local tier = self:ResolveTier(level, maxLevel)
    local skin = self.skins[skinId] or self.skins.sigil
    local layer, resolvedTier = self:ResolveLayer(skin, tier)

    if not layer then
        -- No art defined at or below this tier. Substitute halo rather than
        -- painting nothing: this is the Phase 2 state for the whole flagship,
        -- and it stays correct as Phase 4's art lands tier by tier.
        local halo = self.skins.halo
        local haloLayer = self:ResolveLayer(halo, tier)
        return tier, halo, haloLayer, self:ResolveAccent(halo, classToken)
    end

    return resolvedTier or tier, skin, layer, self:ResolveAccent(skin, classToken)
end

--- Texture path for a class rune strip, or nil when the skin/class has none.
---@param skin table|nil
---@param classToken string|nil
---@return string|nil path
function SigilSkins:GetBandTexture(skin, classToken)
    if not skin or not skin.bandTexture or not self:GetFamily(classToken) then
        return nil
    end
    return string.format(skin.bandTexture, string.lower(classToken))
end

--- Texture path for a class crest, or nil when the skin/class has none.
---@param skin table|nil
---@param classToken string|nil
---@return string|nil path
function SigilSkins:GetCrestTexture(skin, classToken)
    if not skin or not skin.crestTexture or not self:GetFamily(classToken) then
        return nil
    end
    return string.format(skin.crestTexture, string.lower(classToken))
end

--- TexCoord quarter of a rune strip for a tier. One file holds all four tiers,
--- so a tier change is a coordinate change rather than a texture swap.
---
--- The atlas is a 2x2 GRID, not four stacked bands. SkinBand is drawn into the
--- square ring region (ApplySizePreset sizes it ring x ring), and the band art
--- is a ring ornament, so the source rect has to be square too -- slicing the
--- file into four full-width strips would squash every glyph 4:1.
---
---   +----+----+
---   | 1  | 2  |
---   +----+----+
---   | 3  | 4  |
---   +----+----+
---
---@param tier number
---@return number left, number right, number top, number bottom
function SigilSkins:GetBandTexCoord(tier)
    local index = math.max(1, math.min(self.MAX_TIER, tonumber(tier) or 1))
    local zeroBased = index - 1
    local column = zeroBased % 2
    local row = math.floor(zeroBased / 2)
    return column * 0.5, (column + 1) * 0.5, row * 0.5, (row + 1) * 0.5
end
